#include "PythonBackend.h"
#include <fstream>

using namespace std;

PythonBackend::PythonBackend() : indentLevel(0) {}

string PythonBackend::convertBanglaDigits(const string& input) {
    static const string banglaDigits[10] = {"০", "১", "২", "৩", "৪", "৫", "৬", "৭", "৮", "৯"};
    string result = "";
    for (size_t i = 0; i < input.length(); ) {
        bool matched = false;
        for (int d = 0; d < 10; d++) {
            const string& bd = banglaDigits[d];
            if (input.compare(i, bd.length(), bd) == 0) {
                result += to_string(d);
                i += bd.length();
                matched = true;
                break;
            }
        }
        if (!matched) {
            result += input[i];
            i++;
        }
    }
    return result;
}

void PythonBackend::emit(const string& line) {
    outputLines.push_back(line);
}

string PythonBackend::getIndent() const {
    return string(indentLevel * 4, ' ');
}

string PythonBackend::generateExpr(Expr* expr) {
    if (expr == nullptr) return "";

    if (NumberExpr* n = dynamic_cast<NumberExpr*>(expr)) {
        return convertBanglaDigits(n->value);
    }

    if (VariableExpr* v = dynamic_cast<VariableExpr*>(expr)) {
        return v->name;
    }

    if (BinaryExpr* b = dynamic_cast<BinaryExpr*>(expr)) {
        string leftStr = generateExpr(b->left);
        string rightStr = generateExpr(b->right);
        return "(" + leftStr + " " + b->op + " " + rightStr + ")";
    }

    return "";
}

void PythonBackend::generateStmt(Stmt* stmt) {
    if (stmt == nullptr) return;

    if (VarDeclStmt* d = dynamic_cast<VarDeclStmt*>(stmt)) {
        if (d->initValue != nullptr) {
            emit(getIndent() + d->name + " = " + generateExpr(d->initValue));
        } else {
            emit(getIndent() + d->name + " = None");
        }
    }
    else if (AssignStmt* a = dynamic_cast<AssignStmt*>(stmt)) {
        emit(getIndent() + a->name + " = " + generateExpr(a->value));
    }
    else if (PrintStmt* p = dynamic_cast<PrintStmt*>(stmt)) {
        emit(getIndent() + "print(" + generateExpr(p->value) + ")");
    }
    else if (IfStmt* i = dynamic_cast<IfStmt*>(stmt)) {
        emit(getIndent() + "if " + generateExpr(i->condition) + ":");
        indentLevel++;
        if (i->thenBranch.empty()) {
            emit(getIndent() + "pass");
        } else {
            for (Stmt* s : i->thenBranch) {
                generateStmt(s);
            }
        }
        indentLevel--;

        if (!i->elseBranch.empty()) {
            emit(getIndent() + "else:");
            indentLevel++;
            for (Stmt* s : i->elseBranch) {
                generateStmt(s);
            }
            indentLevel--;
        }
    }
    else if (WhileStmt* w = dynamic_cast<WhileStmt*>(stmt)) {
        emit(getIndent() + "while " + generateExpr(w->condition) + ":");
        indentLevel++;
        if (w->body.empty()) {
            emit(getIndent() + "pass");
        } else {
            for (Stmt* s : w->body) {
                generateStmt(s);
            }
        }
        indentLevel--;
    }
    else if (ForStmt* f = dynamic_cast<ForStmt*>(stmt)) {
        if (f->init) generateStmt(f->init);
        string condStr = f->condition ? generateExpr(f->condition) : "True";
        emit(getIndent() + "while " + condStr + ":");
        indentLevel++;
        if (f->body.empty() && !f->update) {
            emit(getIndent() + "pass");
        } else {
            for (Stmt* s : f->body) {
                generateStmt(s);
            }
            if (f->update) {
                generateStmt(f->update);
            }
        }
        indentLevel--;
    }
    else if (ExprStmt* e = dynamic_cast<ExprStmt*>(stmt)) {
        emit(getIndent() + generateExpr(e->expr));
    }
}

string PythonBackend::generate(const vector<Stmt*>& program) {
    outputLines.clear();
    indentLevel = 0;

    emit("# Generated by sylang compiler");
    emit("");

    for (size_t i = 0; i < program.size(); i++) {
        generateStmt(program[i]);
    }

    return getCode();
}

string PythonBackend::generateFromTAC(const vector<TACInstr*>& instructions) {
    outputLines.clear();
    indentLevel = 0;

    emit("# Generated by sylang compiler (from TAC)");
    emit("");

    for (TACInstr* instr : instructions) {
        if (TACBinOp* b = dynamic_cast<TACBinOp*>(instr)) {
            emit(b->dest + " = (" + convertBanglaDigits(b->left) + " " + b->op + " " + convertBanglaDigits(b->right) + ")");
        } else if (TACCopy* c = dynamic_cast<TACCopy*>(instr)) {
            emit(c->dest + " = " + convertBanglaDigits(c->src));
        } else if (TACPrint* p = dynamic_cast<TACPrint*>(instr)) {
            emit("print(" + convertBanglaDigits(p->operand) + ")");
        } else if (TACLabel* l = dynamic_cast<TACLabel*>(instr)) {
            emit("# label " + l->name);
        } else if (TACJump* j = dynamic_cast<TACJump*>(instr)) {
            emit("# goto " + j->target);
        } else if (TACJumpIf* ji = dynamic_cast<TACJumpIf*>(instr)) {
            emit("# ifFalse " + ji->condition + " goto " + ji->target);
        }
    }

    return getCode();
}

string PythonBackend::getCode() const {
    string result = "";
    for (const string& line : outputLines) {
        result += line + "\n";
    }
    return result;
}

bool PythonBackend::writeToFile(const string& filename) const {
    ofstream out(filename);
    if (!out.is_open()) return false;
    out << getCode();
    return true;
}

void PythonBackend::print(ostream& out) const {
    out << getCode();
}
