#include "PythonBackend.h"
#include <fstream>
#include <unordered_map>

using namespace std;

PythonBackend::PythonBackend() : indentLevel(0) {}

string PythonBackend::convertBanglaDigits(const string& input) {
    string result = "";
    for (size_t i = 0; i < input.length(); i++) {
        if (i + 2 < input.length()) {
            unsigned char b1 = input[i];
            unsigned char b2 = input[i + 1];
            unsigned char b3 = input[i + 2];
            // Bengali digits U+09E6 to U+09EF: 0xE0 0xA7 0xA6..0xAF
            if (b1 == 0xE0 && b2 == 0xA7 && b3 >= 0xA6 && b3 <= 0xAF) {
                int digit = b3 - 0xA6;
                result += to_string(digit);
                i += 2;
                continue;
            }
        }
        result += input[i];
    }
    return result;
}

void PythonBackend::emit(const string& line) {
    outputLines.push_back(line);
}

string PythonBackend::getIndent() const {
    return string(indentLevel * 4, ' ');
}

string PythonBackend::generateExpr(Expr* expr) {
    if (expr == nullptr) return "";

    if (NumberExpr* n = dynamic_cast<NumberExpr*>(expr)) {
        return convertBanglaDigits(n->value);
    }

    if (VariableExpr* v = dynamic_cast<VariableExpr*>(expr)) {
        return v->name;
    }

    if (BinaryExpr* b = dynamic_cast<BinaryExpr*>(expr)) {
        string leftStr = generateExpr(b->left);
        string rightStr = generateExpr(b->right);
        return "(" + leftStr + " " + b->op + " " + rightStr + ")";
    }

    return "";
}

void PythonBackend::generateStmt(Stmt* stmt) {
    if (stmt == nullptr) return;

    if (VarDeclStmt* d = dynamic_cast<VarDeclStmt*>(stmt)) {
        if (d->initValue != nullptr) {
            emit(getIndent() + d->name + " = " + generateExpr(d->initValue));
        } else {
            emit(getIndent() + d->name + " = None");
        }
    }
    else if (AssignStmt* a = dynamic_cast<AssignStmt*>(stmt)) {
        emit(getIndent() + a->name + " = " + generateExpr(a->value));
    }
    else if (PrintStmt* p = dynamic_cast<PrintStmt*>(stmt)) {
        emit(getIndent() + "print(" + generateExpr(p->value) + ")");
    }
    else if (IfStmt* i = dynamic_cast<IfStmt*>(stmt)) {
        emit(getIndent() + "if " + generateExpr(i->condition) + ":");
        indentLevel++;
        if (i->thenBranch.empty()) {
            emit(getIndent() + "pass");
        } else {
            for (Stmt* s : i->thenBranch) {
                generateStmt(s);
            }
        }
        indentLevel--;

        if (!i->elseBranch.empty()) {
            emit(getIndent() + "else:");
            indentLevel++;
            for (Stmt* s : i->elseBranch) {
                generateStmt(s);
            }
            indentLevel--;
        }
    }
    else if (WhileStmt* w = dynamic_cast<WhileStmt*>(stmt)) {
        emit(getIndent() + "while " + generateExpr(w->condition) + ":");
        indentLevel++;
        if (w->body.empty()) {
            emit(getIndent() + "pass");
        } else {
            for (Stmt* s : w->body) {
                generateStmt(s);
            }
        }
        indentLevel--;
    }
    else if (ExprStmt* e = dynamic_cast<ExprStmt*>(stmt)) {
        emit(getIndent() + generateExpr(e->expr));
    }
}

string PythonBackend::generate(const vector<Stmt*>& program) {
    outputLines.clear();
    indentLevel = 0;

    emit("# Generated by sylang compiler");
    emit("");

    for (size_t i = 0; i < program.size(); i++) {
        generateStmt(program[i]);
    }

    return getCode();
}

string PythonBackend::generateFromTAC(const vector<TACInstr*>& instructions) {
    outputLines.clear();
    indentLevel = 0;

    emit("# Generated by sylang compiler (from TAC)");
    emit("");

    bool hasControlFlow = false;
    for (TACInstr* instr : instructions) {
        if (dynamic_cast<TACLabel*>(instr) || dynamic_cast<TACJump*>(instr) || dynamic_cast<TACJumpIf*>(instr)) {
            hasControlFlow = true;
            break;
        }
    }

    if (!hasControlFlow) {
        for (TACInstr* instr : instructions) {
            if (TACBinOp* b = dynamic_cast<TACBinOp*>(instr)) {
                emit(b->dest + " = (" + convertBanglaDigits(b->left) + " " + b->op + " " + convertBanglaDigits(b->right) + ")");
            } else if (TACCopy* c = dynamic_cast<TACCopy*>(instr)) {
                emit(c->dest + " = " + convertBanglaDigits(c->src));
            } else if (TACPrint* p = dynamic_cast<TACPrint*>(instr)) {
                emit("print(" + convertBanglaDigits(p->operand) + ")");
            }
        }
    } else {
        // State machine translation for TAC with labels and jumps
        unordered_map<string, int> labelIndex;
        for (size_t i = 0; i < instructions.size(); i++) {
            if (TACLabel* l = dynamic_cast<TACLabel*>(instructions[i])) {
                labelIndex[l->name] = (int)i;
            }
        }

        emit("pc = 0");
        emit("while pc < " + to_string(instructions.size()) + ":");
        indentLevel = 1;

        for (size_t i = 0; i < instructions.size(); i++) {
            string prefix = (i == 0) ? "if" : "elif";
            emit(getIndent() + prefix + " pc == " + to_string(i) + ":");
            indentLevel++;

            TACInstr* instr = instructions[i];
            if (TACBinOp* b = dynamic_cast<TACBinOp*>(instr)) {
                emit(getIndent() + b->dest + " = (" + convertBanglaDigits(b->left) + " " + b->op + " " + convertBanglaDigits(b->right) + ")");
                emit(getIndent() + "pc = " + to_string(i + 1));
            } else if (TACCopy* c = dynamic_cast<TACCopy*>(instr)) {
                emit(getIndent() + c->dest + " = " + convertBanglaDigits(c->src));
                emit(getIndent() + "pc = " + to_string(i + 1));
            } else if (TACPrint* p = dynamic_cast<TACPrint*>(instr)) {
                emit(getIndent() + "print(" + convertBanglaDigits(p->operand) + ")");
                emit(getIndent() + "pc = " + to_string(i + 1));
            } else if (TACLabel* l = dynamic_cast<TACLabel*>(instr)) {
                emit(getIndent() + "# label " + l->name);
                emit(getIndent() + "pc = " + to_string(i + 1));
            } else if (TACJump* j = dynamic_cast<TACJump*>(instr)) {
                int targetPc = labelIndex.count(j->target) ? labelIndex[j->target] : (int)(i + 1);
                emit(getIndent() + "pc = " + to_string(targetPc));
            } else if (TACJumpIf* ji = dynamic_cast<TACJumpIf*>(instr)) {
                int targetPc = labelIndex.count(ji->target) ? labelIndex[ji->target] : (int)(i + 1);
                emit(getIndent() + "if not (" + ji->condition + "):");
                emit(getIndent() + "    pc = " + to_string(targetPc));
                emit(getIndent() + "else:");
                emit(getIndent() + "    pc = " + to_string(i + 1));
            }
            indentLevel--;
        }
        indentLevel = 0;
    }

    return getCode();
}

string PythonBackend::getCode() const {
    string result = "";
    for (const string& line : outputLines) {
        result += line + "\n";
    }
    return result;
}

bool PythonBackend::writeToFile(const string& filename) const {
    ofstream out(filename);
    if (!out.is_open()) return false;
    out << getCode();
    return true;
}

void PythonBackend::print(ostream& out) const {
    out << getCode();
}
